# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mail-classification-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://extractionapiregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_5457409f0cc04033b4855a1d8d290a78 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_655d23cdd1f24883b982e220edaf4f45 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: extractionapiregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5457409f0cc04033b4855a1d8d290a78 }}/mail-api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mail-classification-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1cd429f56176456db546d7a4a9ac6e32 }}
        images: 'extractionapiregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5457409f0cc04033b4855a1d8d290a78 }}/mail-api:${{ github.sha }}'